# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Album' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Album
    pod 'SDWebImage', '~> 4.0'
    pod 'ReachabilitySwift'

  target 'AlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlbumUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
